---
- name: Running myrole end-to-end Deployment(CD)
  hosts: ansibleclient1

  vars_files:
       - /root/ansible/docker_token.yml
       - /root/ansible/myrole/vars/name_vars.yml

  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: radical-weekend-nov-10am-2022
    WORKSPACE: /var/lib/jenkins/workspace/dev-pipeline
    DockerHub_repo: "aamirs/radical-private-repo"
    VER: "nov-2022-0.0.1"

  roles: 
      - /root/ansible/myrole
