- hosts: ansibleclient1
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: /root/ansible/sample.txt
      dest: /tmp 
    register: my_result
  - debug:
      var: my_result
    
    
