---
- name: This sets up a Docker server
  hosts: webservers
  tasks:
  - name: Installing Docker
    yum:
      name: docker
      state: present
  - name: ensure docker is running
    service:
      name: docker
      state: started
  - name: installing docker image
    shell: docker pull centos
    register: shell_result
  - debug: 
      var: shell_result
  - name: Creating test container
    command: "{{ item }}"
    with_items:
    - docker run -itd --name=ansibel_test centos
    - docker run -itd -v /tmp/aamir_directory:/tmp --name=ansibel_vol centos
#    shell: docker run -itd -v /tmp/devops_directory:/tmp  --name=ansibel_vol centos
    register: shell_result
  - debug: 
      var: shell_result
