---
- name: This sets up an httpd webserver
  hosts: radical-bastion
  vars_files:
       - secrets.yml
  vars:
       - destdir: /var/www/html
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: present
      
  - name: Start httpd service
    service:
      name: httpd
      state: started

  - name: Enable service httpd
    service:
      name: httpd
      enabled: yes
      
  - name: running random commands
    command: /usr/bin/cat /root/.ssh/authorized_keys
#  - name: creating index file
#    file:
#      path: "/var/www/html/index.html"
#      state: touch
#  - name: echoing text
#    shell: printf 'Hello' >> /var/www/html/index.html
#    register: shell_result

  - name: Install git packages
    yum:
      name: git
      state: present

  - name: Cloning repository
    git:
       repo: 'https://{{gituser}}:{{gitpass}}@gitlab.com/andromeda99/html.git'
       dest: "{{ destdir }}"
       
  - name: fetching Public IP
    shell: host myip.opendns.com resolver1.opendns.com | grep address
    register: shell_result
  - debug:
      var: shell_result    
    

